# Site settings
title: TO DO....
email: carpediem631@gmail.com
description: "写博客是为了更好的思考"
baseurl: ""
url: "http://linzhihao.github.io"
twitter_username: freetedlin
github_username:  linzhihao

# Build settings
markdown: kramdown
permalink: pretty
